// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetRecordingData, GetRecordingErrors, GetRecordingResponses, HealthCheckData, HealthCheckResponses, ListRecordingsData, ListRecordingsErrors, ListRecordingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check endpoint
 *
 * Check if the service is running and healthy
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List all recordings
 *
 * Retrieve a list of all audio recordings stored in the system
 */
export const listRecordings = <ThrowOnError extends boolean = false>(options?: Options<ListRecordingsData, ThrowOnError>) => (options?.client ?? client).get<ListRecordingsResponses, ListRecordingsErrors, ThrowOnError>({ url: '/api/recordings', ...options });

/**
 * Get a specific recording
 *
 * Retrieve details of a specific audio recording by its ID
 */
export const getRecording = <ThrowOnError extends boolean = false>(options: Options<GetRecordingData, ThrowOnError>) => (options.client ?? client).get<GetRecordingResponses, GetRecordingErrors, ThrowOnError>({ url: '/api/recordings/{id}', ...options });
