// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3002' | (string & {});
};

export type Recording = {
    id: string;
    filename: string;
    format: 'wav' | 'mp3';
    size: number;
    createdAt: string;
    modifiedAt: string;
    hasTranscript: boolean;
    transcriptMetadata?: {
        duration?: number;
        language?: string;
        diarization?: string;
        jobId?: string;
        transcriptCreatedAt?: string;
    };
};

export type _Error = {
    error: string;
};

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Service is healthy
     */
    200: {
        status: string;
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type ListRecordingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/recordings';
};

export type ListRecordingsErrors = {
    /**
     * Server error
     */
    500: _Error;
};

export type ListRecordingsError = ListRecordingsErrors[keyof ListRecordingsErrors];

export type ListRecordingsResponses = {
    /**
     * List of recordings
     */
    200: {
        recordings: Array<Recording>;
        total: number;
    };
};

export type ListRecordingsResponse = ListRecordingsResponses[keyof ListRecordingsResponses];

export type GetRecordingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/recordings/{id}';
};

export type GetRecordingErrors = {
    /**
     * Recording not found
     */
    404: _Error;
    /**
     * Server error
     */
    500: _Error;
};

export type GetRecordingError = GetRecordingErrors[keyof GetRecordingErrors];

export type GetRecordingResponses = {
    /**
     * Recording details
     */
    200: Recording;
};

export type GetRecordingResponse = GetRecordingResponses[keyof GetRecordingResponses];
