// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateTableDocumentData, CreateTableDocumentErrors, CreateTableDocumentResponses, CreateUseCaseData, CreateUseCaseErrors, CreateUseCaseResponses, DeleteTableDocumentData, DeleteTableDocumentErrors, DeleteTableDocumentResponses, DeleteUseCaseData, DeleteUseCaseErrors, DeleteUseCaseResponses, GetTableDocumentData, GetTableDocumentErrors, GetTableDocumentResponses, HealthCheckData, HealthCheckResponses, ListTableDocumentsData, ListTableDocumentsErrors, ListTableDocumentsResponses, PushToConfluenceData, PushToConfluenceErrors, PushToConfluenceResponses, RunAgentData, RunAgentErrors, RunAgentResponses, UpdateTableDocumentData, UpdateTableDocumentErrors, UpdateTableDocumentResponses, UpdateUseCaseData, UpdateUseCaseErrors, UpdateUseCaseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check endpoint
 *
 * Check if the service is running and healthy
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * List all table documents
 *
 * Retrieve a list of all table documents stored in the system
 */
export const listTableDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListTableDocumentsData, ThrowOnError>) => (options?.client ?? client).get<ListTableDocumentsResponses, ListTableDocumentsErrors, ThrowOnError>({ url: '/api/table-documents', ...options });

/**
 * Create a new table document
 *
 * Create a new table document with the provided title and description
 */
export const createTableDocument = <ThrowOnError extends boolean = false>(options: Options<CreateTableDocumentData, ThrowOnError>) => (options.client ?? client).post<CreateTableDocumentResponses, CreateTableDocumentErrors, ThrowOnError>({
    url: '/api/table-documents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a table document
 *
 * Delete a table document and all its associated use cases
 */
export const deleteTableDocument = <ThrowOnError extends boolean = false>(options: Options<DeleteTableDocumentData, ThrowOnError>) => (options.client ?? client).delete<DeleteTableDocumentResponses, DeleteTableDocumentErrors, ThrowOnError>({ url: '/api/table-documents/{id}', ...options });

/**
 * Get a specific table document
 *
 * Retrieve details of a specific table document by its ID
 */
export const getTableDocument = <ThrowOnError extends boolean = false>(options: Options<GetTableDocumentData, ThrowOnError>) => (options.client ?? client).get<GetTableDocumentResponses, GetTableDocumentErrors, ThrowOnError>({ url: '/api/table-documents/{id}', ...options });

/**
 * Update a table document
 *
 * Update the title or description of a table document
 */
export const updateTableDocument = <ThrowOnError extends boolean = false>(options: Options<UpdateTableDocumentData, ThrowOnError>) => (options.client ?? client).patch<UpdateTableDocumentResponses, UpdateTableDocumentErrors, ThrowOnError>({
    url: '/api/table-documents/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create a new use case for a table document
 *
 * Add a new use case to an existing table document
 */
export const createUseCase = <ThrowOnError extends boolean = false>(options: Options<CreateUseCaseData, ThrowOnError>) => (options.client ?? client).post<CreateUseCaseResponses, CreateUseCaseErrors, ThrowOnError>({
    url: '/api/table-documents/{id}/use-cases',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a use case
 *
 * Remove a use case from a table document
 */
export const deleteUseCase = <ThrowOnError extends boolean = false>(options: Options<DeleteUseCaseData, ThrowOnError>) => (options.client ?? client).delete<DeleteUseCaseResponses, DeleteUseCaseErrors, ThrowOnError>({ url: '/api/table-documents/{id}/use-cases/{useCaseId}', ...options });

/**
 * Update a use case
 *
 * Update the details of an existing use case
 */
export const updateUseCase = <ThrowOnError extends boolean = false>(options: Options<UpdateUseCaseData, ThrowOnError>) => (options.client ?? client).patch<UpdateUseCaseResponses, UpdateUseCaseErrors, ThrowOnError>({
    url: '/api/table-documents/{id}/use-cases/{useCaseId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Run agent on a table document
 *
 * Execute an AI agent with a custom prompt on the table document
 */
export const runAgent = <ThrowOnError extends boolean = false>(options: Options<RunAgentData, ThrowOnError>) => (options.client ?? client).post<RunAgentResponses, RunAgentErrors, ThrowOnError>({
    url: '/api/table-documents/{id}/agent',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Push table document to Confluence
 *
 * Export and publish the table document to a Confluence page
 */
export const pushToConfluence = <ThrowOnError extends boolean = false>(options: Options<PushToConfluenceData, ThrowOnError>) => (options.client ?? client).post<PushToConfluenceResponses, PushToConfluenceErrors, ThrowOnError>({
    url: '/api/table-documents/{id}/push-to-confluence',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
