// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BroadcastMessageData, BroadcastMessageErrors, BroadcastMessageResponses, GetHealthData, GetHealthErrors, GetHealthResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Broadcast message to all Socket.IO clients
 *
 * Sends a message to all connected Socket.IO clients on a specified channel.
 * The message will be emitted to all clients listening on the given channel.
 *
 * Request body is validated using Zod schema:
 * - `channel`: Required string, minimum length 1
 * - `payload`: Optional, can be any valid JSON value
 *
 */
export const broadcastMessage = <ThrowOnError extends boolean = false>(options: Options<BroadcastMessageData, ThrowOnError>) => (options.client ?? client).post<BroadcastMessageResponses, BroadcastMessageErrors, ThrowOnError>({
    url: '/api/broadcast',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health check endpoint
 *
 * Returns the health status of the service and the number of connected clients
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/health', ...options });
