// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type _Error = {
    /**
     * Error message describing what went wrong
     */
    error: string;
};

export type BroadcastRequest = {
    /**
     * The Socket.IO event channel to broadcast on
     */
    channel: string;
    /**
     * The payload to send to clients
     */
    payload?: unknown;
};

export type BroadcastResponse = {
    /**
     * Indicates if the broadcast was successful
     */
    success: boolean;
    /**
     * The channel the message was broadcasted on
     */
    channel: string;
    /**
     * Number of connected clients that received the message
     */
    clientCount: number;
};

export type HealthResponse = {
    status: 'ok';
    service: string;
    connectedClients: number;
};

export type BroadcastMessageData = {
    body: {
        /**
         * The Socket.IO event channel to broadcast on
         */
        channel: string;
        /**
         * The payload to send to clients (can be any valid JSON value)
         */
        payload?: {
            [key: string]: unknown;
        } | Array<unknown> | string | number | boolean | unknown;
    };
    path?: never;
    query?: never;
    url: '/api/broadcast';
};

export type BroadcastMessageErrors = {
    /**
     * Bad request - missing or invalid channel
     */
    400: _Error;
    /**
     * Method Not Allowed
     */
    405: _Error;
    /**
     * Internal server error - broadcast failed
     */
    500: _Error;
};

export type BroadcastMessageError = BroadcastMessageErrors[keyof BroadcastMessageErrors];

export type BroadcastMessageResponses = {
    /**
     * Message successfully broadcasted
     */
    200: {
        /**
         * Indicates if the broadcast was successful
         */
        success: boolean;
        /**
         * The channel the message was broadcasted on
         */
        channel: string;
        /**
         * Number of connected clients that received the message
         */
        clientCount: number;
    };
};

export type BroadcastMessageResponse = BroadcastMessageResponses[keyof BroadcastMessageResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Method Not Allowed
     */
    405: _Error;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: {
        /**
         * Health status of the service
         */
        status: 'ok';
        /**
         * Name of the service
         */
        service: string;
        /**
         * Number of currently connected Socket.IO clients
         */
        connectedClients: number;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
